#if !canImport(ObjectiveC)
import XCTest

extension APITests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__APITests = [
        ("testCopyright", testCopyright),
        ("testInvalidHTML", testInvalidHTML),
        ("testLocalized", testLocalized),
        ("testNoColon", testNoColon),
        ("testNoCSS", testNoCSS),
        ("testNoFrame", testNoFrame),
        ("testNoMetadata", testNoMetadata),
        ("testNoTitle", testNoTitle),
        ("testPoorHTML", testPoorHTML),
        ("testRepositoryStructure", testRepositoryStructure),
        ("testRightToLeft", testRightToLeft),
        ("testSiteError", testSiteError),
        ("testSiteValidationError", testSiteValidationError),
        ("testUnknownLocalization", testUnknownLocalization),
        ("testUnlocalized", testUnlocalized),
    ]
}

extension RegressionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RegressionTests = [
        ("testRedirect", testRedirect),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(APITests.__allTests__APITests),
        testCase(RegressionTests.__allTests__RegressionTests),
    ]
}
#endif
