/*
 Resources.swift

 This source file is part of the SDGWeb open source project.
 https://sdggiesbrecht.github.io/SDGWeb

 Copyright ©2019 Jeremy David Giesbrecht and the SDGWeb project contributors.

 Soli Deo gloria.

 Licensed under the Apache Licence, Version 2.0.
 See http://www.apache.org/licenses/LICENSE-2.0 for licence information.
 */

import Foundation

internal enum Resources {}
internal typealias Ressourcen = Resources

extension Resources {
  static let root = String(
    data: Data(
      base64Encoded:
        "LyoKIFJvb3QuY3NzCiAKIFRoaXMgc291cmNlIGZpbGUgaXMgcGFydCBvZiB0aGUgU0RHV2ViIG9wZW4gc291cmNlIHByb2plY3QuCiBodHRwczovL3NkZ2dpZXNicmVjaHQuZ2l0aHViLmlvL1NER1dlYgogCiBDb3B5cmlnaHQgwqkyMDE44oCTMjAxOSBKZXJlbXkgRGF2aWQgR2llc2JyZWNodCBhbmQgdGhlIFNER1dlYiBwcm9qZWN0IGNvbnRyaWJ1dG9ycy4KIAogU29saSBEZW8gZ2xvcmlhLgogCiBMaWNlbnNlZCB1bmRlciB0aGUgQXBhY2hlIExpY2VuY2UsIFZlcnNpb24gMi4wLgogU2VlIGh0dHA6Ly93d3cuYXBhY2hlLm9yZy9saWNlbnNlcy9MSUNFTlNFLTIuMCBmb3IgbGljZW5jZSBpbmZvcm1hdGlvbi4KICovCgovKiDigKLigKLigKLigKLigKLigKLigKIgTGF5b3V0IOKAouKAouKAouKAouKAouKAouKAoiAqLwoKLyogRmlsbCB2aWV3cG9ydCAqLwpodG1sLCBib2R5IHsKICBtYXJnaW46IDA7CiAgcGFkZGluZzogMDsKICBtaW4td2lkdGg6IDEwMHZ3OwogIG1pbi1oZWlnaHQ6IDEwMHZoOwp9CgovKiBSZW1vdmUgbmF2aWdhdGlvbiBmcm9tIHByaW50ICovCkBtZWRpYSBwcmludCB7CiAgbmF2IHsKICAgIGRpc3BsYXk6IG5vbmU7CiAgfQp9CgovKiBUcmVhdCBuYXZpZ2F0aW9uIGxpbmtzIGFzIGJsb2NrIGVsZW1lbnRzICovCm5hdiA+IGEgewogICAgZGlzcGxheTogYmxvY2s7Cn0KCi8qIEJvb2vigJBzdHlsZSBwYXJhZ3JhcGhzICovCnAgewogIHRleHQtaW5kZW50OiAzZW07Cn0KcCB7CiAgdGV4dC1hbGlnbjoganVzdGlmeTsKICBoeXBoZW5zOiBhdXRvOwp9Cgo6bm90KHApICsgcCB7CiAgbWFyZ2luLXRvcDogMC41ZW07Cn0KcCArIDpub3QocCkgewogIG1hcmdpbi10b3A6IDAuNWVtOwp9CnA6bGFzdC1jaGlsZCB7CiAgbWFyZ2luLWJvdHRvbTogMC41ZW07Cn0KCi8qIOKAouKAouKAouKAouKAouKAouKAoiBDb2xvdXJzIOKAouKAouKAouKAouKAouKAouKAoiAqLwoKLyogU3RhbmRhcmRpemUgY29sb3VycyAqLwpodG1sIHsKICBiYWNrZ3JvdW5kLWNvbG9yOiAjRkZGRkZGOwogIGNvbG9yOiAjMDAwMDAwOwp9CgovKiBSZW1vdmUgbGlua3MgZnJvbSBwcmludCAqLwpAbWVkaWEgcHJpbnQgewogIGEgewogICAgY29sb3I6IGluaGVyaXQ7CiAgfQp9CgovKiDigKLigKLigKLigKLigKLigKLigKIgRm9udHMg4oCi4oCi4oCi4oCi4oCi4oCi4oCiICovCgpodG1sIHsKICBmb250LWZhbWlseTogc2VyaWY7Cn0KQG1lZGlhIG9ubHkgc2NyZWVuIHsKICBodG1sIHsKICAgIGZvbnQtZmFtaWx5OiBzYW5zLXNlcmlmOwogIH0KfQoKLyog4oCi4oCi4oCi4oCi4oCi4oCi4oCiIFNlbWFudGljIFRleHQgRm9ybWF0dGluZyDigKLigKLigKLigKLigKLigKLigKIgKi8KCnNwYW5bbGFuZ10geyAvKiBGb3JlaWduIGxhbmd1YWdlLiAqLwogIGZvbnQtc3R5bGU6IGl0YWxpYzsKfQoKLyogUmVtb3ZlIGxpbmtzIGZyb20gcHJpbnQgKi8KQG1lZGlhIHByaW50IHsKICBhIHsKICAgIGZvbnQtd2VpZ2h0OiBpbmhlcml0CiAgICB0ZXh0LWRlY29yYXRpb246IGluaGVyaXQ7CiAgfQp9Cg=="
    )!,
    encoding: String.Encoding.utf8
  )!

}
