#if !canImport(ObjectiveC)
import XCTest

extension SDGHTMLAPITests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SDGHTMLAPITests = [
        ("testEscaping", testEscaping),
        ("testHTMLElement", testHTMLElement),
        ("testParsing", testParsing),
        ("testPercentEncoding", testPercentEncoding),
        ("testRedirect", testRedirect),
        ("testSyntaxError", testSyntaxError),
        ("testTextDirection", testTextDirection),
        ("testValidLink", testValidLink),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SDGHTMLAPITests.__allTests__SDGHTMLAPITests),
    ]
}
#endif
