#if !canImport(ObjectiveC)
import XCTest

extension SDGHTMLAPITests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SDGHTMLAPITests = [
        ("testAttribute", testAttribute),
        ("testAttributes", testAttributes),
        ("testAttributeValue", testAttributeValue),
        ("testClosingTag", testClosingTag),
        ("testComment", testComment),
        ("testContent", testContent),
        ("testDocument", testDocument),
        ("testElement", testElement),
        ("testElementContinuation", testElementContinuation),
        ("testEscaping", testEscaping),
        ("testListSyntax", testListSyntax),
        ("testOpeningTag", testOpeningTag),
        ("testParsing", testParsing),
        ("testPercentEncoding", testPercentEncoding),
        ("testRedirect", testRedirect),
        ("testSyntaxError", testSyntaxError),
        ("testText", testText),
        ("testTextDirection", testTextDirection),
        ("testValidLink", testValidLink),
    ]
}

extension SDGHTMLRegressionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SDGHTMLRegressionTests = [
        ("testValidationOfMultiScalarClusters", testValidationOfMultiScalarClusters),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SDGHTMLAPITests.__allTests__SDGHTMLAPITests),
        testCase(SDGHTMLRegressionTests.__allTests__SDGHTMLRegressionTests),
    ]
}
#endif
